base_url = "https://bryantconquest.com"
compile_sass = true
build_search_index = true

# Theme Options
theme = "hyde"

title = "626c75"
title1 = "626c75 Homepage"
description = "Short Tech Write Ups"

highlight_code = true
highlight_theme = "one-dark"

analytics = "<script async src='https://www.googletagmanager.com/gtag/js?id=UA-166300934-1'></script> <script> window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'UA-166300934-1');</script>"

[extra]
hyde_theme = "theme-base-10"
hyde_sticky = true
hyde_links = [
{url = "https://github.com/BConquest", name = "Github"},
{url = "/about", name = "About"},
]
