base_url = "https://bryantconquest.com"
compile_sass = true
highlight_code = true
build_search_index = true

# Theme Options
theme = "hyde"

[extra]
hyde_theme = "theme-base-08"
hyde_sticky = true
hyde_links = [
{url = "/", name = "Home"},
{url = "https://github.com/BConquest", name = "Github"},
]
