base_url = "https://bryantconquest.com"
compile_sass = true
build_search_index = true

# Theme Options
theme = "hyde"

title = "626c75"
description = "Short Tech Write Ups"

highlight_code = true
highlight_theme = "one-dark"

[extra]
hyde_theme = "theme-base-10"
hyde_sticky = true
hyde_links = [
{url = "https://github.com/BConquest", name = "Github"},
{url = "/about", name = "About"},
]
