base_url = "https://bryantconquest.com"
compile_sass = true
highlight_code = true
build_search_index = true

# Theme Options
theme = "hyde"

title = "626c75"
description = "Short Tech Write Ups"

[extra]
hyde_theme = "theme-base-0d"
hyde_sticky = true
hyde_links = [
{url = "https://github.com/BConquest", name = "Github"},
{url = "/", name = "About"},
]
