base_url = "https://bryantconquest.com"
compile_sass = true
build_search_index = true

# Theme Options
theme = "hera"

title = "626c75"
title1 = "626c75 Homepage"
description = "Short Tech Write Ups"

highlight_code = true
highlight_theme = "one-dark"


[extra]
hera_theme = "theme-base-10"
hera_sticky = true
hera_links = [
{url = "https://github.com/BConquest", name = "Github"},
{url = "/about", name = "About"},
{url = "/blog", name = "Blog"},
{url = "/projects", name = "Projects"},
]
